# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions
name: Node CI

on:
  [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: npm install, build-main
        run: |
          npm install
          npm run build-main --if-present
      - name: Archive production artifacts
        uses: actions/upload-artifact@v2
        with:
          name: hydra
          path: |
            /
            